[project]
name = "collection-manager"
version = "0.1.0"
authors = ["Kostas Kokkoros <mavroprovato@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "requests~=2.32.3",
    "pyqt5~=5.15.11",
    "mutagen~=1.47.0",
    "sqlalchemy~=2.0.34",
    "pillow~=12.1.0"
]
